name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build
      env:
        CI_KEYCHAIN_SECRET: ${{ secrets.CI_KEYCHAIN_SECRET }}
      run: make build ci-sign BUILD_ARGS='$(RELEASE_BUILD_ARGS)' CODESIGN_IDENTITY="ci0.code.beeper-tools.com" KC_PASSWORD=$CI_KEYCHAIN_SECRET KC_PATH=ci.keychain
      
    - name: Locate build artifact
      run: cp $(make --silent product-path BUILD_ARGS='$(RELEASE_BUILD_ARGS)') imserver
  
    - name: 'Upload imserver'
      uses: actions/upload-artifact@v3
      with:
        name: imserver
        path: imserver
        retention-days: 45
